packages:
  - "server/"
  - "libraries/base/"
  - "sites/*"
  - "desktop/"

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - contentlayer
  - contentlayer2
  - protobufjs

overrides:
  "@isaacs/brace-expansion@<=5.0.0": ">=5.0.1"
  ajv@<6.14.0: ">=6.14.0"
  devalue@<=5.6.2: ">=5.6.3"
  devalue@>=5.1.0 <5.6.2: ">=5.6.2"
  devalue@>=5.3.0 <=5.6.1: ">=5.6.2"
  diff@>=6.0.0 <8.0.3: ">=8.0.3"
  hono@<4.11.10: ">=4.11.10"
  hono@<4.11.7: ">=4.11.7"
  lodash-es@>=4.0.0 <=4.17.22: ">=4.17.23"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@<3.1.3: ">=3.1.3"
  minimatch@<3.1.4: ">=3.1.4"
  minimatch@>=10.0.0 <10.2.1: ">=10.2.1"
  minimatch@>=10.0.0 <10.2.3: ">=10.2.3"
  minimatch@>=5.0.0 <5.1.7: ">=5.1.7"
  minimatch@>=5.0.0 <5.1.8: ">=5.1.8"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  node-forge@<1.3.2: ">=1.3.2"
  qs@<6.14.1: ">=6.14.1"
  qs@>=6.7.0 <=6.14.1: ">=6.14.2"
  rollup@>=4.0.0 <4.59.0: ">=4.59.0"
  serialize-javascript@<=7.0.2: ">=7.0.3"
  seroval@<1.4.1: ">=1.4.1"
  seroval@<=1.4.0: ">=1.4.1"
  tar@<7.5.7: ">=7.5.7"
  tar@<7.5.8: ">=7.5.8"
  tar@<=7.5.2: ">=7.5.3"
  tar@<=7.5.3: ">=7.5.4"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"

  cross-spawn@<6.0.6: ">=6.0.6"
  cross-spawn@>=7.0.0 <7.0.5: ">=7.0.5"
  form-data@<2.5.4: ">=2.5.4"
  got@<11.8.5: ">=11.8.5"
  http-cache-semantics@<4.1.1: ">=4.1.1"
  lodash@<4.17.21: ">=4.17.21"
  lodash@>=4.0.0 <4.17.21: ">=4.17.21"
  minimist@>=1.0.0 <1.2.6: ">=1.2.6"
  nth-check@<2.0.1: ">=2.0.1"
  semver-regex@<3.1.3: ">=3.1.3"
  semver-regex@<3.1.4: ">=3.1.4"
  semver@>=7.0.0 <7.5.2: ">=7.5.2"
  sharp@<0.30.5: ">=0.30.5"
  sharp@<0.32.6: ">=0.32.6"
  tmp@<=0.2.3: ">=0.2.4"
  tough-cookie@<4.1.3: ">=4.1.3"
  trim-newlines@<3.0.1: ">=3.0.1"

shamefullyHoist: true
