onlyBuiltDependencies:
  - "@bufbuild/buf"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

shamefullyHoist: true
