name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: webiny/action-conventional-commits@7bb50f43f6d33ca0449067e674c7c8fdd013b70a # v1.3.1